### ISSUE TITLE
Set scan parameters failed: Operation not permitted

### ISSUE THREAD

**Issue by matthiasbock** [interoberlin/Wunderbar-Python-SDK#2]
<pre>
demos$ ./scan_wunderbars.py
Traceback (most recent call last):
  File "./scan_wunderbars.py", line 95, in <module>
    scan_wunderbars()
  File "./scan_wunderbars.py", line 73, in scan_wunderbars
    devices = scan_ble_devices(name_filter='Wunderbar.*')
  File "/usr/local/lib/python2.7/dist-packages/relayr/ble.py", line 100, in scan_ble_devices
    conn.expect('LE Scan \.+', timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/pexpect/__init__.py", line 1418, in expect
    timeout, searchwindowsize)
  File "/usr/lib/python2.7/dist-packages/pexpect/__init__.py", line 1433, in expect_list
    timeout, searchwindowsize)
  File "/usr/lib/python2.7/dist-packages/pexpect/__init__.py", line 1521, in expect_loop
    raise EOF(str(err) + '\n' + str(self))
pexpect.EOF: End Of File (EOF). Exception style platform.
<pexpect.spawn object at 0x7ffbc2256ed0>
version: 3.2
command: /usr/bin/timeout
args: ['/usr/bin/timeout', '1', 'hcitool', 'lescan']
searcher: <pexpect.searcher_re object at 0x7ffbc2256e90>
buffer (last 100 chars): ''
before (last 100 chars): 'Set scan parameters failed: Operation not permitted\r\n'
after: <class 'pexpect.EOF'>
match: None
match_index: None
exitstatus: 1
flag_eof: True
pid: 15682
child_fd: 4
closed: False
timeout: 30
delimiter: <class 'pexpect.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
</pre>

**Comment by matthiasbock** [comment]
Running as root helps, but is a security risk

http://unix.stackexchange.com/questions/96106/bluetooth-le-scan-as-non-root
