### ISSUE TITLE
'NoneType' object has no attribute 'groupdict'

### ISSUE THREAD

**Issue by matthiasbock** [interoberlin/Wunderbar-Python-SDK#3]
<pre>
$ ./scan_wunderbars.py 
Discovered device: xx:xx:xx:xx:xx:xx WunderbarLIGHT 
Traceback (most recent call last):
  File "./scan_wunderbars.py", line 95, in <module>
    scan_wunderbars()
  File "./scan_wunderbars.py", line 77, in scan_wunderbars
    chars = d.characteristics()
  File "/usr/local/lib/python2.7/dist-packages/relayr/ble.py", line 178, in characteristics
    lines = [re.match(pat, line).groupdict() for line in lines]
AttributeError: 'NoneType' object has no attribute 'groupdict'
</pre>

**Comment by matthiasbock** [comment]
There's something wrong with the regular expression handling in the Relayr SDK's ble.py file.

http://stackoverflow.com/questions/15232832/python-regex-attributeerror-nonetype-object-has-no-attribute-groups

**Comment by matthiasbock** [comment]
The code is not checking for regular expression mismatches.
The following patch for ble.py fixes the issue:

<pre>
...
        # example line format:
        # 'handle = 0x0002, char properties = 0x02, char value handle = 0x0003, uuid = 00002a00-0000-1000-8000-00805f9b34fb'
        cmd = 'gatttool -t random -b %s --characteristics' % self.addr
        if uuid:
            cmd += ' --uuid=%s' % uuid
        res = subprocess.check_output(shlex.split(cmd))
        lines = re.split('\r?\n', res)
        pat = '^handle\s*=\s*(?P<name_handle>0x[0-9a-fA-F]{4}),\s*char\s*properties\s*=\s*(?P<properties>0x[0-9a-fA-F]+),\s*char\s*value\s*handle\s*=\s*(?P<value_handle>0x[0-9a-fA-F]{4}),\s*uuid\s*=\s*(?P<uuid>[0-9a-fA-F\-]+)'
        parsed_lines = [(re.match(pat, line).groupdict() if re.match(pat, line) else None) for line in lines]
        self.data['characteristics'] = []
        for line in parsed_lines:
            if not line is None:
                short = line['uuid'].split('-')[0]
                while short[0] == '0': short = short[1:]
                line['_uuid'] = short
                self.data['characteristics'].append(line)
        return self.data['characteristics']
...
</pre>
